
// This file strictly generated by AI as a note which I can come to understanding priority queues in advanced when the right time hits. 

/*
        A Priority Queue sounds like a queue, but it is not FIFO. The idea is simple:
        the element with the highest priority leaves first, even if it arrived later.

        Think about a hospital emergency room. A patient with a heart attack arrives
        after a patient with a headache, but gets treated first. That is exactly how
        a priority queue works.

        Now, what operations do we care about?

        1) Insert a new element with a priority.
        2) Remove the highest-priority element.
        3) See the highest-priority element without removing it.

        Suppose we use a normal unsorted array.

        Insertion is easy: put the element at the end. O(1)

        But removing the highest priority is expensive because we must scan the whole
        array to find the largest element. O(n)

        What if we keep the array sorted?

        Now the highest-priority element is always at one end, so removal is O(1).
        But insertion becomes O(n) because elements may need to be shifted.

        So arrays force a trade-off: either insertion is fast or deletion is fast.

        Can we make both reasonably fast? Yes, with a HEAP.

        A heap is a complete binary tree with a special rule.

        For a max-heap:
        every parent is greater than or equal to its children.

        This means the largest element is always at the root.

        Important: the heap is NOT fully sorted. Only the parent-child relationship
        is maintained.

        Insertion process:

        1) Put the new element in the next available position at the bottom.
        2) Compare it with its parent.
        3) If it is larger, swap upward.
        4) Continue until the heap property is restored.

        This upward movement is called heapify-up or sift-up.

        How many swaps can happen?
        At most the height of the tree.

        A complete binary tree with n elements has height about log n,
        so insertion is O(log n).

        Removal process:

        1) The largest element is at the root.
        2) Remove the root.
        3) Move the last element to the root.
        4) Push it downward by swapping with the larger child until the heap property
        becomes valid again.

        This is heapify-down or sift-down.

        Again, at most the tree height is traversed, so removal is O(log n).

        Peeking the highest-priority element is simply looking at the root, so O(1).

        Final complexities:

        Insert                 O(log n)
        Remove highest         O(log n)
        Peek highest           O(1)

        Why do we usually implement heaps using arrays instead of linked nodes?

        Because a complete binary tree has a very regular structure.
        If a node is at index i:

        left child   = 2*i + 1
        right child  = 2*i + 2
        parent       = (i - 1) / 2

        No pointers are needed.

        Priority Queue vs Heap:

        Priority Queue is the abstract idea:
        "remove the highest-priority element first."

        Heap is one implementation of that idea.

        Max-priority queue:
        largest value removed first.

        Min-priority queue:
        smallest value removed first.

        When empty?
        size == 0.

        When full?
        If using a fixed-size array, full when size == capacity.
        If using a dynamic array (vector), practically only memory limits it.

        The best mental model:
        A normal queue is a waiting line.
        A priority queue is a competition.
        Every new element competes for a better position, and the current champion
        always stays at the root.

*/